sudo: required
language: java
jdk:
  - oraclejdk11
before_install:
  - chmod u+x gradlew
script:
  - gradle assemble
before_deploy:
  - export RELEASE_JAR_FILE=$(ls build/libs/*.jar)
deploy:
  provider: releases
  api_key: '$API_KEY'
  file_glob: true
  file: "${RELEASE_JAR_FILE}"
  skip_cleanup: true
on:
  tags: true