version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info --no-daemon

branches:
  only:
    - master

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
- JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0